-- Dot Trading Post — what people call things.
--
-- Run before matching.sql (setup.sql runs everything in order).
--
-- People write the same thing many ways: PS5, PlayStation 5, ps 5; Pokémon, pokemon tcg, pkmn.
-- Each phrase here names a thing: the first term is what it is, and the rest are broader things
-- it also counts as. A listing that HAS "Charizard" gets charizard, pokemon and tcg as keywords,
-- so someone who wants "pokemon cards" finds it. A listing that WANTS "Charizard" gets only
-- charizard, so it isn't matched with every Pokémon card on the board. Matching only ever widens
-- in the direction that is true.
--
-- Add a row to teach the board a new name; then bump match_terms_version in matching.sql so
-- existing listings are re-read.

create table if not exists public.app_config (key text primary key, value text not null);
alter table public.app_config enable row level security;

create table if not exists public.match_aliases (
  phrase text primary key check (phrase ~ '^[a-z0-9]+( [a-z0-9]+)*$'),
  terms  text[] not null check (cardinality(terms) between 1 and 8)
);
alter table public.match_aliases enable row level security;
drop policy if exists "aliases are public" on public.match_aliases;
create policy "aliases are public" on public.match_aliases for select using (true);

-- Lowercase, accents off (Pokémon = Pokemon), anything else a single space, padded with spaces
-- so a phrase can be found as whole words.
create or replace function public.match_norm(t text) returns text
language sql immutable as $$
  select ' ' || btrim(regexp_replace(translate(lower(coalesce(t, '')), 'áàâäãåāéèêëēíìîïīóòôöõøōúùûüūñçýÿ', 'aaaaaaaeeeeeiiiiiooooooouuuuuncyy'), '[^a-z0-9]+', ' ', 'g')) || ' '
$$;

insert into public.match_aliases (phrase, terms) values
  ('pokemon', '{pokemon,tcg}'),
  ('pokemon tcg', '{pokemon,tcg}'),
  ('pokemon card', '{pokemon,tcg}'),
  ('pokemon cards', '{pokemon,tcg}'),
  ('pkmn', '{pokemon,tcg}'),
  ('ptcg', '{pokemon,tcg}'),
  ('pikachu', '{pikachu,pokemon,tcg}'),
  ('charizard', '{charizard,pokemon,tcg}'),
  ('mewtwo', '{mewtwo,pokemon,tcg}'),
  ('mew', '{mew,pokemon,tcg}'),
  ('eevee', '{eevee,pokemon,tcg}'),
  ('blastoise', '{blastoise,pokemon,tcg}'),
  ('venusaur', '{venusaur,pokemon,tcg}'),
  ('gengar', '{gengar,pokemon,tcg}'),
  ('lugia', '{lugia,pokemon,tcg}'),
  ('umbreon', '{umbreon,pokemon,tcg}'),
  ('rayquaza', '{rayquaza,pokemon,tcg}'),
  ('snorlax', '{snorlax,pokemon,tcg}'),
  ('gyarados', '{gyarados,pokemon,tcg}'),
  ('dragonite', '{dragonite,pokemon,tcg}'),
  ('magic the gathering', '{mtg,tcg}'),
  ('magic gathering', '{mtg,tcg}'),
  ('mtg', '{mtg,tcg}'),
  ('yu gi oh', '{yugioh,tcg}'),
  ('yugioh', '{yugioh,tcg}'),
  ('ygo', '{yugioh,tcg}'),
  ('one piece tcg', '{onepiece,tcg}'),
  ('one piece card', '{onepiece,tcg}'),
  ('one piece cards', '{onepiece,tcg}'),
  ('lorcana', '{lorcana,tcg}'),
  ('disney lorcana', '{lorcana,tcg}'),
  ('sports card', '{sportscard}'),
  ('sports cards', '{sportscard}'),
  ('baseball card', '{sportscard}'),
  ('baseball cards', '{sportscard}'),
  ('basketball card', '{sportscard}'),
  ('basketball cards', '{sportscard}'),
  ('football card', '{sportscard}'),
  ('football cards', '{sportscard}'),
  ('hockey card', '{sportscard}'),
  ('hockey cards', '{sportscard}'),
  ('topps', '{topps,sportscard}'),
  ('panini', '{panini,sportscard}'),
  ('prizm', '{panini,sportscard}'),
  ('psa', '{graded}'),
  ('bgs', '{graded}'),
  ('cgc', '{graded}'),
  ('beckett', '{graded}'),
  ('graded', '{graded}'),
  ('ngc', '{graded}'),
  ('pcgs', '{graded}'),
  ('slab', '{graded}'),
  ('slabbed', '{graded}'),
  ('booster box', '{booster,sealed,tcg}'),
  ('booster boxes', '{booster,sealed,tcg}'),
  ('booster pack', '{booster,sealed,tcg}'),
  ('booster packs', '{booster,sealed,tcg}'),
  ('etb', '{etb,sealed,pokemon,tcg}'),
  ('elite trainer box', '{etb,sealed,pokemon,tcg}'),
  ('ps5', '{ps5,playstation,sony,console}'),
  ('ps 5', '{ps5,playstation,sony,console}'),
  ('playstation 5', '{ps5,playstation,sony,console}'),
  ('playstation five', '{ps5,playstation,sony,console}'),
  ('ps4', '{ps4,playstation,sony,console}'),
  ('ps 4', '{ps4,playstation,sony,console}'),
  ('playstation 4', '{ps4,playstation,sony,console}'),
  ('playstation four', '{ps4,playstation,sony,console}'),
  ('ps3', '{ps3,playstation,sony,console,retro}'),
  ('ps 3', '{ps3,playstation,sony,console,retro}'),
  ('playstation 3', '{ps3,playstation,sony,console,retro}'),
  ('ps2', '{ps2,playstation,sony,console,retro}'),
  ('ps 2', '{ps2,playstation,sony,console,retro}'),
  ('playstation 2', '{ps2,playstation,sony,console,retro}'),
  ('ps1', '{ps1,playstation,sony,console,retro}'),
  ('psx', '{ps1,playstation,sony,console,retro}'),
  ('psone', '{ps1,playstation,sony,console,retro}'),
  ('ps one', '{ps1,playstation,sony,console,retro}'),
  ('playstation 1', '{ps1,playstation,sony,console,retro}'),
  ('psp', '{psp,playstation,sony,handheld}'),
  ('ps vita', '{vita,playstation,sony,handheld}'),
  ('psvita', '{vita,playstation,sony,handheld}'),
  ('playstation vita', '{vita,playstation,sony,handheld}'),
  ('playstation', '{playstation,sony,console}'),
  ('xbox series x', '{xboxseries,xbox,microsoft,console}'),
  ('xbox series s', '{xboxseries,xbox,microsoft,console}'),
  ('series x', '{xboxseries,xbox,microsoft,console}'),
  ('series s', '{xboxseries,xbox,microsoft,console}'),
  ('xbox one', '{xboxone,xbox,microsoft,console}'),
  ('xbox 360', '{xbox360,xbox,microsoft,console,retro}'),
  ('original xbox', '{xboxog,xbox,microsoft,console,retro}'),
  ('xbox', '{xbox,microsoft,console}'),
  ('nintendo switch', '{switch,nintendo,console}'),
  ('switch oled', '{switch,nintendo,console}'),
  ('switch lite', '{switch,nintendo,console}'),
  ('switch 2', '{switch,nintendo,console}'),
  ('nintendo switch 2', '{switch,nintendo,console}'),
  ('n64', '{n64,nintendo,console,retro}'),
  ('nintendo 64', '{n64,nintendo,console,retro}'),
  ('snes', '{snes,nintendo,console,retro}'),
  ('super nintendo', '{snes,nintendo,console,retro}'),
  ('super nes', '{snes,nintendo,console,retro}'),
  ('super famicom', '{snes,nintendo,console,retro}'),
  ('nes', '{nes,nintendo,console,retro}'),
  ('famicom', '{nes,nintendo,console,retro}'),
  ('nintendo entertainment system', '{nes,nintendo,console,retro}'),
  ('gamecube', '{gamecube,nintendo,console,retro}'),
  ('game cube', '{gamecube,nintendo,console,retro}'),
  ('wii u', '{wiiu,nintendo,console}'),
  ('wiiu', '{wiiu,nintendo,console}'),
  ('wii', '{wii,nintendo,console}'),
  ('game boy', '{gameboy,nintendo,handheld,retro}'),
  ('gameboy', '{gameboy,nintendo,handheld,retro}'),
  ('game boy color', '{gbc,gameboy,nintendo,handheld,retro}'),
  ('gameboy color', '{gbc,gameboy,nintendo,handheld,retro}'),
  ('gbc', '{gbc,gameboy,nintendo,handheld,retro}'),
  ('game boy advance', '{gba,gameboy,nintendo,handheld,retro}'),
  ('gameboy advance', '{gba,gameboy,nintendo,handheld,retro}'),
  ('gba', '{gba,gameboy,nintendo,handheld,retro}'),
  ('gba sp', '{gba,gameboy,nintendo,handheld,retro}'),
  ('nintendo ds', '{ds,nintendo,handheld}'),
  ('nds', '{ds,nintendo,handheld}'),
  ('ds lite', '{ds,nintendo,handheld}'),
  ('dsi', '{ds,nintendo,handheld}'),
  ('3ds', '{3ds,nintendo,handheld}'),
  ('2ds', '{3ds,nintendo,handheld}'),
  ('new 3ds', '{3ds,nintendo,handheld}'),
  ('3ds xl', '{3ds,nintendo,handheld}'),
  ('nintendo', '{nintendo}'),
  ('sega genesis', '{genesis,sega,console,retro}'),
  ('mega drive', '{genesis,sega,console,retro}'),
  ('megadrive', '{genesis,sega,console,retro}'),
  ('genesis console', '{genesis,sega,console,retro}'),
  ('dreamcast', '{dreamcast,sega,console,retro}'),
  ('sega saturn', '{saturn,sega,console,retro}'),
  ('game gear', '{gamegear,sega,handheld,retro}'),
  ('master system', '{mastersystem,sega,console,retro}'),
  ('sega', '{sega}'),
  ('atari', '{atari,console,retro}'),
  ('atari 2600', '{atari,console,retro}'),
  ('neo geo', '{neogeo,console,retro}'),
  ('neogeo', '{neogeo,console,retro}'),
  ('steam deck', '{steamdeck,handheld,valve}'),
  ('rog ally', '{rogally,handheld}'),
  ('retro game', '{retro}'),
  ('retro games', '{retro}'),
  ('retro gaming', '{retro}'),
  ('vintage game', '{retro}'),
  ('vintage games', '{retro}'),
  ('cartridge', '{cartridge}'),
  ('cartridges', '{cartridge}'),
  ('cart', '{cartridge}'),
  ('carts', '{cartridge}'),
  ('cib', '{cib}'),
  ('complete in box', '{cib}'),
  ('video game', '{videogame}'),
  ('video games', '{videogame}'),
  ('console', '{console}'),
  ('consoles', '{console}'),
  ('handheld', '{handheld}'),
  ('handhelds', '{handheld}'),
  ('funko', '{funko,figure}'),
  ('funko pop', '{funko,figure}'),
  ('funko pops', '{funko,figure}'),
  ('pop vinyl', '{funko,figure}'),
  ('lego', '{lego}'),
  ('legos', '{lego}'),
  ('hot wheels', '{diecast}'),
  ('hotwheels', '{diecast}'),
  ('matchbox car', '{diecast}'),
  ('matchbox cars', '{diecast}'),
  ('diecast', '{diecast}'),
  ('die cast', '{diecast}'),
  ('beanie baby', '{beanie}'),
  ('beanie babies', '{beanie}'),
  ('action figure', '{figure}'),
  ('action figures', '{figure}'),
  ('figurine', '{figure}'),
  ('figurines', '{figure}'),
  ('comic', '{comic}'),
  ('comics', '{comic}'),
  ('comic book', '{comic}'),
  ('comic books', '{comic}'),
  ('graphic novel', '{comic}'),
  ('vinyl record', '{vinyl,music}'),
  ('vinyl records', '{vinyl,music}'),
  ('lp', '{vinyl,music}'),
  ('lps', '{vinyl,music}'),
  ('vinyl', '{vinyl}'),
  ('iphone', '{iphone,apple,phone}'),
  ('ipad', '{ipad,apple,tablet}'),
  ('macbook', '{macbook,apple,laptop}'),
  ('airpods', '{airpods,apple,headphones}'),
  ('laptop', '{laptop}'),
  ('laptops', '{laptop}'),
  ('notebook computer', '{laptop}'),
  ('headphones', '{headphones}'),
  ('earbuds', '{headphones}'),
  -- NFTs, and the chains they live on (a listed NFT gets nft and its chain as keywords).
  ('nft', '{nft}'),
  ('nfts', '{nft}'),
  ('digital art', '{nft}'),
  ('digital collectible', '{nft}'),
  ('digital collectibles', '{nft}'),
  ('jpeg', '{nft}'),
  ('jpegs', '{nft}'),
  ('pfp', '{pfp,nft}'),
  ('pfps', '{pfp,nft}'),
  ('on base', '{basechain}'),
  ('base chain', '{basechain}'),
  ('base nft', '{basechain}'),
  ('base nfts', '{basechain}'),
  ('eth', '{ethereum}'),
  ('mainnet', '{ethereum}'),
  ('matic', '{polygon}'),
  ('avax', '{avalanche}'),
  ('bsc', '{bnb}'),
  ('bnb chain', '{bnb}'),
  ('arb', '{arbitrum}'),
  ('physical', '{physical}'),
  ('irl', '{physical}'),
  ('in real life', '{physical}'),
  ('real life', '{physical}')
on conflict (phrase) do update set terms = excluded.terms;
