import { chromium, VENDOR, OUT, ROOT, CSP, legacyBoard } from "./harness.mjs";
const A = "11111111-1111-4111-8111-111111111111", X = "22222222-2222-4222-8222-222222222222", Y = "33333333-3333-4333-8333-333333333333";
const b64 = o => Buffer.from(JSON.stringify(o)).toString("base64url"); const exp = Math.floor(Date.now() / 1000) + 86400;
const jwt = b64({ alg: "HS256", typ: "JWT" }) + "." + b64({ sub: A, role: "authenticated", aud: "authenticated", exp, iat: exp - 86400, session_id: "s" }) + ".sig";
const sess = { access_token: jwt, token_type: "bearer", expires_in: 86400, expires_at: exp, refresh_token: "r", user: { id: A, email: "a@x.com", aud: "authenticated", role: "authenticated", app_metadata: {}, user_metadata: {}, created_at: new Date().toISOString() } };
const t = i => new Date(Date.UTC(2026, 9, i)).toISOString();
const done = (id, from, ex) => ({ id, item_id: "zz", owner_id: A, from_id: from, status: "done", confirm_owner: true, confirm_from: true, created_at: t(Number(id.slice(1))), ...ex });
const signals = [done("s1", X, { swapped: true }), done("s2", X), done("s3", X), done("s4", Y)];
const items = [{ id: "i1", owner_id: X, title: "Charizard holo", want: "", cat: "Trading Cards", status: "open", created_at: t(1), photos: ["https://example.invalid/a.jpg", "https://example.invalid/b.jpg"] },
               { id: "i2", owner_id: A, title: "Lamp", want: "", cat: "Home & Kitchen", status: "open", created_at: t(1) },
               { id: "i3", owner_id: A, title: "Old mug", want: "", cat: "Home & Kitchen", status: "removed", created_at: t(1) }];
const res = []; const ok = (n, c, x) => res.push((c ? "PASS " : "FAIL ") + n + (x ? "  [" + x + "]" : ""));
const b = await chromium.launch({}).catch(() => chromium.launch());
const p = await (await b.newContext({ viewport: { width: 1100, height: 1200 } })).newPage(); const rpcs = [];
  await p.route(/127\.0\.0\.1:8765\/app\.html/, async r => { const resp = await r.fetch(); r.fulfill({ response: resp, headers: { ...resp.headers(), "content-security-policy": CSP } }); });
  p.on("console", m => { if (/Content Security Policy/i.test(m.text())) res.push("CSPVIOLATION " + m.text().slice(0, 200)); });
p.on("pageerror", e => res.push("PAGEERROR " + e.message)); p.on("dialog", d => d.accept());
const hdr = { "access-control-allow-origin": "*" };
await p.route(/cdn\.jsdelivr\.net\/.*supabase\.js/, r => r.fulfill({ path: VENDOR + "/supabase.js", contentType: "application/javascript", headers: hdr }));
await p.route(/cdnjs\.cloudflare\.com\/.*ethers/, r => r.fulfill({ path: VENDOR + "/ethers.js", contentType: "application/javascript", headers: hdr }));
await p.route(/fonts\.|example\.invalid|functions\/v1|api\/nft/, r => r.fulfill({ status: 404, body: "" }));
await p.route(/supabase\.co\/rest\/v1\/(\w+)/, r => { const tb = r.request().url().match(/rest\/v1\/(\w+)/)[1];
  r.fulfill({ status: 200, contentType: "application/json", body: JSON.stringify({ items, offers: [], profiles: [{ id: A, name: "Trader 1A2B", area: "Leeds" }, { id: X, name: "Xena" }, { id: Y, name: "Yuri" }], offer_signals: signals, verification_badges: [{ id: "v", item_id: "i1", owner_id: X, status: "verified", verified_at: t(3), summary: "Code legible.", score: 80 }], messages: [] }[tb] || []) }); });
await p.route(/supabase\.co\/rest\/v1\/rpc\/(\w+)/, r => { rpcs.push(r.request().url().match(/rpc\/(\w+)/)[1]); r.fulfill({ status: 200, contentType: "application/json", body: '"removed"' }); });
await p.route(/supabase\.co\/(auth|realtime)/, r => r.fulfill({ status: 200, contentType: "application/json", body: JSON.stringify(sess.user) }));
await legacyBoard(p); await p.goto("http://127.0.0.1:8765/app.html", { waitUntil: "domcontentloaded" });
await p.evaluate(([s]) => localStorage.setItem("sb-yujxwfghmauajrpduagl-auth-token", JSON.stringify(s)), [sess]);
await p.reload({ waitUntil: "domcontentloaded" }); await p.waitForTimeout(1500);
ok("pinned scripts still load", await p.evaluate(() => !!(window.supabase && window.ethers)));
const card = "#feed .item:has-text('Charizard')";
ok("photos have descriptive alt text", (await p.$$eval(card + " img", i => i.map(x => x.alt))).join("|") === "Charizard holo — photo 1 of 2|Charizard holo — photo 2 of 2");
ok("proof badge shows no link to the photo", !(await p.$(card + " a.proof")) && /Verified/.test(await p.$eval(card + " .proof", e => e.title)));
ok("nudge asks for a name while it's the anonymous default", !(await p.$eval("#nudge", e => e.hidden)));
await p.click("#t-mine"); await p.waitForTimeout(200);
const ledger = await p.$eval("#myLedger", e => e.innerText.replace(/\n/g, " | "));
ok("dots: repeat partner counts half then nothing; verified and vouches per person", (await p.$eval("#myDots", e => e.textContent)) === "9", ledger.slice(0, 200));
ok("a removed listing isn't shown under Your items", (await p.$$eval("#myItems .item h3", h => h.map(x => x.textContent))).join() === "Lamp");
await p.click("#myItems button:has-text('Remove')"); await p.waitForTimeout(500);
ok("Remove goes through remove_item", rpcs.includes("remove_item"));
ok("toasts are announced to screen readers", /Taken off the board/.test(await p.$eval(".sr[aria-live]", e => e.textContent)));
await p.click("#t-browse"); await p.click(card + " button:has-text('Offer a trade')"); await p.waitForTimeout(200);
const dlg = await p.$eval(".veil > .sheet", e => [e.getAttribute("role"), e.getAttribute("aria-modal"), e.getAttribute("aria-label")]);
ok("sheets are labelled modal dialogs with focus inside", dlg[0] === "dialog" && dlg[1] === "true" && dlg[2] === "Offer a trade" && await p.evaluate(() => document.querySelector(".sheet").contains(document.activeElement)));
await p.keyboard.press("Escape"); await p.waitForTimeout(150);
ok("Escape closes the sheet and focus returns", !(await p.$(".veil")) && await p.evaluate(() => /Offer a trade/.test(document.activeElement && document.activeElement.textContent || "")));
await b.close(); console.log(res.join("\n"));
